from random import randint

Attack = ["chafed",
          "scratched",
          "gashed",
          "clawed",
          "lacerated",
          "wrestled",
          "ravaged",
          "gored",
          "pecked",
          "kicked",
          "bruised",
          "grappled",
          "pecked",
          "speared",
          "sliced",
          "clocked",
          "stabbed",
          "clobbered"]

NameList = ["Clora",
            "Raeann",
            "Hildegarde",
            "Leon",
            "Katharina",
            "Trudi",
            "Marisol",
            "Susannah",
            "Weston",
            "Kerri",
            "Sylvia",
            "Xenia",
            "Mildred",
            "Nickole",
            "Kristine",
            "Franklyn",
            "Ernestine",
            "Cedrick",
            "Chanell",
            "Micaela",
            "Cherish",
            "Carson",
            "Darrel",
            "Hallie",
            "Monserrate",
            "Charlott",
            "Suzanna",
            "Hsiu",
            "Lenard",
            "Shante",
            "Jewell",
            "Sachiko",
            "Barabara",
            "Alva",
            "Phillis",
            "Douglas",
            "Talisha",
            "Maritza",
            "Yoshiko",
            "Shenita",
            "Pete",
            "Bart",
            "Nickie",
            "Pierre",
            "Maryland",
            "Katia",
            "Belkis",
            "Esta",
            "Louetta",
            "Merry"]


def random_name():
    return NameList[randint(0, len(NameList) - 1)]


def random_attack():
    return Attack[randint(0, len(Attack) - 1)]
